before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/prometheus/common/version.Version={{ .Version}}
  - -X github.com/prometheus/common/version.Revision={{ .Commit }}
  - -X github.com/prometheus/common/version.Branch={{ .Branch }}
  - -X github.com/prometheus/common/version.BuildUser={{ .Env.USER }}
  - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
