{
 "title": "Netcup SCP",
 "tags": [
  "Prometheus",
  "Netcup"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(scp_build_info, job)"
    }
   },
   {
    "name": "nickname",
    "label": "Nickname",
    "query": {
     "query": "label_values(scp_server_status{job=~\"$job\"}, nickname)"
    }
   },
   {
    "name": "vserver",
    "label": "vServer",
    "query": {
     "query": "label_values(scp_server_status{job=~\"$job\", nickname=~\"$nickname\"}, vserver)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#vServers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(scp_server_status{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Online vServers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_server_status{job=~\"$job\"}) / count(scp_server_status{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_cpu_cores{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_memory_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#Disk space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_disk_capacity_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Monthly Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_monthlytraffic_total_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#recommended Reboots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(scp_config_changed{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#active Rescues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scp_rescue_active{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Server List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "scp_server_status{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_cpu_cores{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_ip_info{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_config_changed{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_rescue_active{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "time() - scp_server_start_time_seconds{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_memory_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_disk_capacity_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_disk_optimization{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_disk_used_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    },
    {
     "expr": "scp_disk_used_bytes{job=~\"$job\", vserver=~\"$vserver\"} / scp_disk_capacity_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  { "title": "Server Details for $vserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "vserver" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_server_status{job=~\"$job\",vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Servers Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "scp_server_status{job=~\"$job\", vserver=~\"$vserver\"}",
     "legendFormat": "{{vserver}} / {{nickname}}"
    }
   ]
  },
  {
   "title": "Reboot recommended?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_config_changed{job=~\"$job\",vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Running since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - scp_server_start_time_seconds{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  { "title": "Monthly traffic", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total monthly traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_monthlytraffic_total_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "scp_monthlytraffic_in_bytes{job=~\"$job\", vserver=~\"$vserver\"}",
     "legendFormat": "incoming"
    },
    {
     "expr": "scp_monthlytraffic_out_bytes{job=~\"$job\", vserver=~\"$vserver\"}",
     "legendFormat": "outgoing"
    }
   ]
  },
  {
   "title": "Incoming traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_monthlytraffic_in_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_monthlytraffic_out_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  { "title": "Disk space", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Disk space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_disk_capacity_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "scp_disk_capacity_bytes{job=~\"$job\", vserver=~\"$vserver\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "scp_disk_used_bytes{job=~\"$job\", vserver=~\"$vserver\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_disk_used_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  },
  {
   "title": "Disk space used %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scp_disk_used_bytes{job=~\"$job\", vserver=~\"$vserver\"} / scp_disk_capacity_bytes{job=~\"$job\", vserver=~\"$vserver\"}"
    }
   ]
  }
 ]
}